services:
  telegram-bot-buddy:
    build:
      context: .
      dockerfile: Dockerfile

    image: telegram-bot-buddy:latest

    container_name: telegram-bot-buddy

    restart: unless-stopped

    ports:
      - "7072:7072"

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_DRIVER: oracle.jdbc.OracleDriver
      WALLET_PATH: /wallet

      # Limit Java heap
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx256m"

    volumes:
      - /home/ubuntu/wallet:/wallet:ro

    # Docker memory limit
    mem_limit: 512m

    # Prevent unlimited CPU usage
    cpus: "1.0"

    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge