version: '3.9'

services:
  telegram-bot-buddy:
    image: telegram-bot-buddy:latest
    container_name: telegram-bot-buddy
    restart: unless-stopped
    ports:
      - "7072:7072"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_DRIVER: oracle.jdbc.OracleDriver
      WALLET_PATH: /wallet

    volumes:
      - /home/ubuntu/wallet:/wallet:ro
    env_file:
      - /home/ubuntu/.env

    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge