spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 3
    driver-class-name: ${DATABASE_DRIVER}
    url: jdbc:oracle:thin:@stock_tp?TNS_ADMIN=${WALLET_PATH}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  application:
    name: telegram-bot-buddy
  jpa:
     show-sql: false
     open-in-view: false
server:
  servlet:
    context-path: /telegram-bot-buddy
  port: 7072
logging:
  level:
    root: INFO
    org:
      telegram:
        telegrambots:
          updatesreceivers:
            DefaultBotSession: OFF

